FROM golang:1.10-alpine

RUN apk add --update \
    build-base \
    curl \
    git \
&& rm -rf /var/cache/apk/*

RUN go get -u golang.org/x/vgo

COPY . $GOPATH/src/gerrit.instructure.com/ddb-sync
WORKDIR $GOPATH/src/gerrit.instructure.com/ddb-sync

RUN vgo install .
