FROM golang:1.11-rc-alpine

RUN apk add --update --no-cache \
    build-base \
    curl \
    clang \
    git

# Enable go 1.11 modules as "auto" won't work because we are in the GOPATH
ENV GO111MODULE=on

COPY . $GOPATH/src/gerrit.instructure.com/ddb-sync
WORKDIR $GOPATH/src/gerrit.instructure.com/ddb-sync

RUN go install ./...
